package com.dtoskfer.presupuesto.pojo;
// Generated Sep 9, 2016 9:10:24 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;

/**
 * TcComputadora generated by hbm2java
 */
public class TcComputadora {

	private int computadoraId;
	private String hostname;
	private String direccionIp;
	private Date fechaRegistro;

	public TcComputadora() {
	}

	public TcComputadora(int computadoraId, String hostname, Date fechaRegistro) {
		this.computadoraId = computadoraId;
		this.hostname = hostname;
		this.fechaRegistro = fechaRegistro;
	}

	public int getComputadoraId() {
		return this.computadoraId;
	}

	public void setComputadoraId(int computadoraId) {
		this.computadoraId = computadoraId;
	}

	public String getHostname() {
		return this.hostname;
	}

	public void setHostname(String hostname) {
		this.hostname = hostname;
	}

	public String getDireccionIp() {
		return this.direccionIp;
	}

	public void setDireccionIp(String direccionIp) {
		this.direccionIp = direccionIp;
	}

	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

}
